apiVersion: v1
entries:
  sentinel-chart:
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2021-09-01T15:13:51.134129+03:00"
    description: A Helm chart to deploy veriteos-charts/sentinel app.
    digest: 418e0c15c47cf40951db5198c607f55bba4041d4bcff49df286d102d7ae47734
    name: sentinel-chart
    type: application
    urls:
    - sentinel-chart-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-09-01T15:13:51.133714+03:00"
    description: A Helm chart to deploy veriteos-charts/sentinel app.
    digest: a87164fd0fe5bec3b942ad1da9f3b7bd56b35e0ae5f4c6b753e122504bb676f8
    name: sentinel-chart
    type: application
    urls:
    - sentinel-chart-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-09-01T15:13:51.133274+03:00"
    description: A Helm chart to deploy veriteos-charts/sentinel app.
    digest: ed315f40e9bfd262af1e555c1d86a3acec54dc260be2923c17801ff3291be9ea
    name: sentinel-chart
    type: application
    urls:
    - sentinel-chart-0.1.0.tgz
    version: 0.1.0
generated: "2021-09-01T15:13:51.132312+03:00"
