apiVersion: v1
entries:
  sentinel-chart:
    - apiVersion: v2
      appVersion: 0.1.0
      created: "2021-08-31T17:40:43.170401+03:00"
      description: A Helm chart to deploy veriteos-charts/sentinel app.
      digest: a87164fd0fe5bec3b942ad1da9f3b7bd56b35e0ae5f4c6b753e122504bb676f8
      name: sentinel-chart
      type: application
      urls:
        - sentinel-chart-0.1.1.tgz
      version: 0.1.1
    - apiVersion: v2
      appVersion: 0.1.0
      created: "2021-08-31T17:40:43.169423+03:00"
      description: A Helm chart to deploy veriteos-charts/sentinel app.
      digest: ed315f40e9bfd262af1e555c1d86a3acec54dc260be2923c17801ff3291be9ea
      name: sentinel-chart
      type: application
      urls:
        - sentinel-chart-0.1.0.tgz
      version: 0.1.0
generated: "2021-08-31T17:40:43.168812+03:00"
