# Default values for sentinel-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "sentinel-test"

deployment:
  # a valid api key is needed for the sentinel agent to forward metadata to veriteos apis
  apiKey: ""
  apiHost: "api.veriteos.com"
  environment: "dev"

  server:
    image: "veriteospublic/sentinel-server"
    tag: "0.0.5"
    replicas: 1

  agent:
    name: "companyName"
    image: "veriteospublic/sentinel-worker"
    tag: "0.0.5"
    replicas: 1

  redpanda:
    image: "vectorized/redpanda"
    tag: "release-20.11.6"
    replicas: 1
