apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-redpanda-configmap
  labels:
    app: sentinel
  namespace: "{{ .Values.namespace }}"
data:
  redpanda.yaml: |-
    cluster_id: ""
    config_file: /etc/redpanda/redpanda.yaml
    license_key: ""
    node_uuid: RKQqZTpZYjyPaPGDqCXZ2Pq4SKMcG8TcKTeXXyp6sfVLUs1pn
    organization: ""
    redpanda:
      admin:
        address: 0.0.0.0
        port: 9644
      advertised_kafka_api:
        address: sentinel-redpanda
        port: 9092
      #advertised_rpc_api:
      #  address: ""
      #  port: 0
      auto_create_topics_enabled: true
      data_directory: /var/lib/redpanda/data
      developer_mode: false
      kafka_api:
        address: 0.0.0.0
        port: 9092
      kafka_api_tls:
        cert_file: ""
        enabled: false
        key_file: ""
        truststore_file: ""
      node_id: 1
      rpc_server:
        address: 0.0.0.0
        port: 33145
      seed_servers: []
      group_max_session_timeout_ms: 90000
    rpk:
      coredump_dir: /var/lib/redpanda/coredump
      enable_memory_locking: false
      enable_usage_stats: true
      overprovisioned: false
      tls:
        cert_file: ""
        key_file: ""
        truststore_file: ""
      tune_aio_events: false
      tune_clocksource: false
      tune_coredump: false
      tune_cpu: false
      tune_disk_irq: false
      tune_disk_nomerges: false
      tune_disk_scheduler: false
      tune_fstrim: false
      tune_network: false
      tune_swappiness: false
      tune_transparent_hugepages: false
