apiVersion: v1
kind: Service
metadata:
  name: sentinel-redpanda
  namespace: "{{ .Values.namespace }}"
  labels:
    app: sentinel-redpanda
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: sentinel-redpanda
