apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel-redpanda
  labels:
    app: sentinel-redpanda
  namespace: "{{ .Values.namespace }}"
spec:
  # prettier-ignore
  replicas: {{ .Values.deployment.redpanda.replicas }}
  selector:
    matchLabels:
      app: sentinel-redpanda
  serviceName: sentinel-redpanda
  template:
    metadata:
      labels:
        app: sentinel-redpanda
    spec:
      containers:
        - name: redpanda
          image: "{{ .Values.deployment.redpanda.image }}:{{ .Values.deployment.redpanda.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: sentinel-redpanda-configmap
              mountPath: /etc/redpanda/
      volumes:
        - name: sentinel-redpanda-configmap
          configMap:
            name: sentinel-redpanda-configmap
